#!/bin/bash

vpnvaihtoehto="$(ip a | grep SWE | grep inet | wc -l)"

if [ "$vpnvaihtoehto" = 1 ]; then
	printf "%s" $(ip a | grep SWE | awk NR==1'{ print $2 }' | sed s/://)
else
		printf "%s" None
fi
exit
